### ISSUE TITLE
Ability to locate policies from specific domains

### ISSUE THREAD

**Issue by bpfoley45** [Skatterbrainz/GPODoc#4]
In multi-domain environments, it would be useful to be able to specify the domain within the Get-GPOComment cmdlet to be passed as an optional parameter to the `Get-GPO -All` cmdlet.

**Comment by Skatterbrainz** [comment]
Question: Would you prefer running this in one domain, with prompts for credentials to use in other/remote domains, or just run this in each domain using session account as default credentials?

**Comment by Skatterbrainz** [comment]
Uploaded changes to support this in 1.2.0 branch.  Please test and confirm?  Thank you!

**Comment by Skatterbrainz** [comment]
I don't see where this provides an obvious benefit over just running it under the proper shell context, either explicit authentication or via implicit trust authentication.  Unless I get a follow-up to this I may drop it.  Please let me know?
